config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root    'static_pages#home'
  get     '/help',      to: 'static_pages#help'
  get     '/about',     to:  'static_pages#about'
  get     '/contact',   to:  'static_pages#contact'
  get     '/signup',    to: 'users#new'
  get     '/login',     to:'sessions#new'
  post    '/login',     to:'sessions#create'
  delete  '/logout',    to:'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { email.downcase! } # same as self.email = self.email.downcase or self.email = email.downcase
  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  class << self
    def digest(string)
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  def authenticated?(remember_token)
    return false unless remember_digest

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def session_token
    remember_digest || remember
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: user_params[:email])
    if @user&.authenticate(user_params[:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      log_in @user
      redirect_to forwarding_url || @user
    else
      flash.now[:danger] = 'Invalid email/password combination.'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def user_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, only: %i[index edit update destroy]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid? && @user.save
      log_in @user
      flash[:success] = 'Welcome to the Sample App'
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      flash[:danger] = 'Please provide valid entries'
      render :edit
    end
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def login_required
    unless logged_in?
      store_original_url
      flash[:danger] = 'PLease log in'
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    redirect_to login_url unless correct_user?(@user)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = 'Rails Tutorial Sample App'
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    session[:session_token] = user.session_token
  end

  def current_user
    if (user_id = session[:user_id])
      user = User.find_by(id: session[:user_id])
      @current_user ||= user if user&.session_token == session[:session_token]
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end

  def correct_user?(user)
    user && user == current_user
  end

  def store_original_url
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer class=" footer container-fluid">
  <small>
    The <a href="http:www.railstutorial.org">Ruby on Rails tutorial</a>
    by <a href="htttp:www.michaelhartl.com">Michael Hartl</a>
  </small>
  <ul>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
    <li><a href="http:www.railstutorial.org">News</a></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
          id="bs-example-navbar-collapse-1">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile",  current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title%></title>
    <%= render 'layouts/rails_default' %>
    <%=render "layouts/shim"  %>
  </head>
  <body>
    <%= render "layouts/header"  %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div,message,class: "alert alert-#{message_type}") %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development?%>
</body>
</html>

app/views/shared/_error_messages.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count,'error')%>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%provide(:title,"About")%>
<h1>About</h1>
<p>
  <a href="http://www.railstutorial.org/"></a>
  <em>Ruby on Rails tutorial</em>
  is a 
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://www.screencasts.railstutorial.org/">screencast series</a>
  to teach web development with <a href="http://www.railstutorial.org/">Ruby on Rails</a>.
  This is the sample app
</p>

app/views/static_pages/contact.html.erb
<%provide(:title,"Contact")%>
<h1>Contact Info</h1>
<p>
  <h3>Samrood Ali</h3>
  <h4>myemail@gmail.com</h4>
</p>

app/views/static_pages/help.html.erb
<%provide(:title,"Help")%>
<h1>Help</h1>
<a href="http://www.railstutorial.org/#help">Get help on the Ruby on Rails Tutorial </a><br>
<a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em></a>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>This is the home page for the <a href="http://www.railstutorial.org/">
      Ruby on Rails tutorial</a> sample application.</h2>
  <%= link_to 'Sign up now',signup_path ,class:"btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.svg",alt:"Rails logo",width:200),
            "http://rubyonrails.org" %>

app/views/users/_form.html.erb
<h1><%= yield(:header) %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, local: true do |form|%>
      <%= render 'shared/error_messages' %>
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
      <%= form.label :email %>
      <%= form.email_field :email ,class:"form-control"%>
      <%= form.label :password %>
      <%= form.password_field :password ,class:"form-control"%>
      <%= form.label :password_confirmation,"Confirmation" %>
      <%= form.password_field :password_confirmation ,class:"form-control"%>
      <%= form.submit "Update my account", class:"btn btn-primary" %>
    <% end %>
    <%# for editing user form only %>
    <% if !@user.new_record? %>
      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="https://gravatar.com/emails" target="_blank" rel="noopener"> change</a>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<li><%=link_to gravatar_for(user,size: 80), user%>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !correct_user?(user) %>
    | <%= link_to 'delete', user, method: :delete ,data:{confirm:'Are you sure'}%>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title,"Settings") %>
<% provide(:header,"Update your profile") %>
<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title,"All users") %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title,"Sign up") %>
<% provide(:header, "Sign up") %>
<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title,@user.name.capitalize) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name.capitalize  %>
      </h1>
    </section>
  </aside>
</div>